server {
    listen 80;
    server_name vaishapp.duckdns.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vaishapp.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/vaishapp.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vaishapp.duckdns.org/privkey.pem;

    location /api {
        proxy_pass http://backend:5000/api;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
